sudo: required

services: docker

before_install:
  - docker-compose up --build

script:
  - docker-compose exec --env 'RAILD_ENV=test' rails db:create
  - docker-compose exec --env 'RAILD_ENV=test' rails db:migrate
  - docker-compose exec --env 'RAILD_ENV=test' rails test